Navbar SignUp and Logo issue solved
IAmTamal/Milan pull request #563
Opened 2022-12-20 17:15 UTC by AbhiPatel10

# Fixes Issue

**My PR closes #562  **
**My PR closes #560  **

# Changes proposed

## What were you told to do ?

## What did you do ?

Sign Up Button render Before Contact Us page so I Solved That issue.

Clicking on logo is re load the Entire page so i solved that issue.

---

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

# Screenshots

![image](https://user-images.githubusercontent.com/76242769/208726289-2f4a95ef-a709-4b68-a4a6-6fcbf5ecfff4.png)

2022-12-20 20:16 UTC, imvedanshmehra approved these changes

2022-12-22 15:54 UTC, IAmTamal requested changes
everything looks great however we might wanna fix this:

![image](https://user-images.githubusercontent.com/72851613/209172510-27e7729f-6706-4c8e-ac13-15b9a2d7f85b.png)

Whenever we hover there's a difference in background color of the button, maybe we can fix this

2022-12-22 19:53 UTC, AbhiPatel10 commented
Done Done, I change what you say above. and also add responsive in Navbar.

2022-12-24 08:47 UTC, AbhiPatel10 commented
Please accept the PR if everything is good.

2022-12-25 18:24 UTC, merged