FEAT: Added Product Details Page
IAmTamal/Milan pull request #624
Opened 2023-04-10 10:51 UTC by DevShobhit

## Related Issue #613 

Closes: #613  

#### Describe the changes you've made ✍
- Created new component `ProductDetails.jsx` 
- Created `ProductDetails.css`
- Changed `DetailedProduct` Component
- Added Route for DetailedProduct inside `App.jsx`

#### Screenshots

![image](https://user-images.githubusercontent.com/74463904/230887467-ceb3ed02-5a51-4181-8baf-ee629cb97d7c.png)
![image](https://user-images.githubusercontent.com/74463904/230887869-a08a69fe-d1fb-4327-808f-4a3c413cc6e0.png)

2023-04-12 06:10 UTC, IAmTamal commented
@DevShobhit , please fix the PR title. Take a look and read at what the bot says !

2023-04-13 06:10 UTC, IAmTamal commented on src/components/shop/ProductDetails.jsx
Can we have the `svg` in separate files ?

2023-04-13 06:11 UTC, IAmTamal requested changes
Rest looks good to me, however, can we add a `<Link>` to the products on the cards so that they take me to the details page ?

2023-04-19 04:57 UTC, DevShobhit commented on src/components/shop/ProductDetails.jsx
Yes, that's a good idea

2023-04-19 07:18 UTC, DevShobhit commented
> Rest looks good to me, however, can we add a `<Link>` to the products on the cards so that they take me to the details page ?

@IAmTamal We can add a button at the bottom of products card. As this would require changing the structure of product card, we can create a new issue for adding button at the bottom of products card and creating Api for fetching product details.

Should I proceed to make changes to product card and create Api for fetching product details with this PR?

2023-05-21 14:45 UTC, closed without merging