fixes #627: button styling of register, login and explore button
IAmTamal/Milan pull request #628
Opened 2023-04-13 19:35 UTC by Unknownempire

## Related Issue 

Closes: #627 

#### Describe the changes you've made ✍
- updated the hover styling of Login, Register and Explore button

2023-04-16 14:51 UTC, Deva-1903 approved these changes

2023-04-16 14:51 UTC, Deva-1903 commented
Looks good 🎉

2023-04-24 05:08 UTC, IAmTamal requested changes
Hi @Unknownempire  , please resolve the conflicts. 

Other than that,
**Amazing work,**
This looks good to me, will be merged soon 🎉.

2023-05-01 08:55 UTC, IAmTamal commented
### Notice 🚩
I am **closing** this Pull request because the contributor is inactive. This will be worked upon by someone else.

Thanks,
Tamal.

2023-05-01 08:55 UTC, closed without merging