refactor: applying the button component
IAmTamal/Milan pull request #691
Opened 2023-05-16 08:22 UTC by vatsalsinghkv

## fix: custom button component to fix inconsistency

Closes: #644 

#### Describe the changes you've made ✍

- Have created custom `button` component, with the following props:
    - `variant`: `solid` (default) | `outline`
    - `to`: null (default) - pass the `to` prop with url to use this button as a `Link`
    - `size`: null (default) | `sm` - used in the navbar
    - `...rest`: rest button props can be passed
- Replaced the buttons with the `Button` component

2023-05-17 09:06 UTC, IAmTamal requested changes
The rest of the changes are looking good to me however I do have some minor changes for you. Please look at the video below (turn up the volume too)

https://github.com/IAmTamal/Milan/assets/72851613/fea46162-502e-436e-9035-3c73c11333eb

2023-05-17 09:06 UTC, IAmTamal commented on src/components/SingleClubEvent.jsx
> +  // const expand = () => {
You can remove these commented codes as they were previously been used but not now at all.

2023-05-17 15:15 UTC, vatsalsinghkv commented
@IAmTamal about the size of the button on the banner (hero section), do I have to reduce the size of buttons everywhere or just on the banner?

2023-05-17 16:27 UTC, IAmTamal commented
> @IAmTamal about the size of the buttons on the banner (hero section), do I have to reduce the size of buttons everywhere or just on the banner?

Just on the home screen. You can compare it to the currently deployed [site](https://milaan.vercel.app/)

2023-05-21 02:37 UTC, IAmTamal approved these changes
**Amazing work,**
This looks good to me, will be merged soon 🎉.

2023-05-21 02:43 UTC, merged