feat: add error 404 page
IAmTamal/Milan pull request #736
Opened 2023-05-23 12:30 UTC by him-raw99

## Related Issue of adding a custom error404 page

Closes: #698 

#### changes That I made ✍
> Added a Error page
> Updated Routing
> Made error page responsive
> Used pre existing components and classes (Made sure to follow the overall theme and color schema).

#### Screenshots 

![image](https://github.com/IAmTamal/Milan/assets/97152850/db91b2fb-a80f-4a2a-aef9-39c752f4ad4f)

kindly comment if you find something wrong with this branch

2023-05-23 12:35 UTC, him-raw99 commented
> We require all PRs to follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/). More details 👇🏼
> 
> ```
>  No release type found in pull request title "Add error 404 page". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/
> 
> Available types:
>  - feat: A new feature
>  - fix: A bug fix
>  - docs: Documentation only changes
>  - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
>  - refactor: A code change that neither fixes a bug nor adds a feature
>  - perf: A code change that improves performance
>  - test: Adding missing tests or correcting existing tests
>  - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
>  - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
>  - chore: Other changes that don't modify src or test files
>  - revert: Reverts a previous commit
> ```

I am sorry, I have updated it now. thanks for you patience.

2023-05-24 17:39 UTC, IAmTamal requested changes
The rest looks good to me.

2023-05-24 17:39 UTC, IAmTamal commented on src/assets/pictures/error404.svg
The SVG file is too big on screen, please reduce it - so that it's centered and we all enjoy a Minimal vibe !

2023-05-24 18:04 UTC, him-raw99 commented on src/assets/pictures/error404.svg
on it.

2023-05-24 18:23 UTC, him-raw99 commented
>I have reduced the size of SVG file to about 50% of screen width and its centered.

>along with that I have changed the button text to just "HOMEPAGE" to improve the overall dynamics of the web-page.

kindly let me know if it needs some more work.

2023-05-26 14:49 UTC, IAmTamal approved these changes
**Amazing work,**
This looks good to me, will be merged soon 🎉.

2023-05-26 16:15 UTC, merged