Update README.md
IAmTamal/Milan pull request #737
Opened 2023-05-23 13:23 UTC by S-ishita

## Related Issue 

Closes: #719 

#### Describe the changes you've made ✍
added badges in readme

#### Screenshots (if any) 📸

2023-05-23 14:14 UTC, S-ishita commented
done @IAmTamal

2023-05-24 13:42 UTC, S-ishita commented
is it ok now? @IAmTamal

2023-05-24 17:56 UTC, IAmTamal requested changes
The rest looks good.
Always test your changes by looking at the `Preview`

2023-05-24 17:56 UTC, IAmTamal commented on README.md
> +<p align="left"><img src="https://img.shields.io/github/license/IAmTamal/Milan?style=for-the-badge" /></p>
Move this badge to the top as well, and add an anchor tag to it  - so that whenever I click on that badge I land in the license page.

2023-05-24 17:56 UTC, IAmTamal commented on README.md
> +</div>
There's no gap after the `</div>` and the next line as a result the bold text is breaking.
Currently, it looks like this : 

![image](https://github.com/IAmTamal/Milan/assets/72851613/30727ad7-df23-4774-a978-49add6506f4c)


Please move the badges to the top : 

![image](https://github.com/IAmTamal/Milan/assets/72851613/cd507d68-e024-4bf2-bb90-7afe001c5351)

2023-05-26 16:18 UTC, IAmTamal commented on README.md
> +<img src="https://img.shields.io/github/package-json/v/IAmTamal/Milan?style=for-the-badge" />
Make sure whenever i click on the version image, it takes me to the [releases](https://github.com/IAmTamal/Milan/releases) page.

2023-05-26 16:32 UTC, S-ishita commented on README.md
> +<img src="https://img.shields.io/github/package-json/v/IAmTamal/Milan?style=for-the-badge" />
done

2023-05-27 04:35 UTC, IAmTamal approved these changes
**Amazing work,**
This looks good to me, will be merged soon 🎉.

2023-05-27 16:42 UTC, merged